print(15*"-")
print("Cadastro")
print(15*"-")
nome = input("Digite Seu Nome: ")
email = input("Digite Seu Email: ")
escola = input("Digite O Nome Da Sua Escola: ")
print("---------------")
print("Cadastro Concluido")
print("---------------")
print("Usuário(a):",nome)
print("Email:",email)
print("Escola:",escola)